### ISSUE TITLE
Shadowsocks无法安装

### ISSUE THREAD

**Issue by jwangb7111** [monlor/MIXBOX-ARCHIVE#222]
请输入你的选择：23
确定要安装shadowsocks插件？[1/0] 1
【Tools】: 开始安装【shadowsocks】插件...
【Tools】: 下载插件安装文件...
【Tools】: 解压安装文件...
【Tools】: 文件解压失败！

按任意键返回.

**Comment by XavierZhang** [comment]
遇到了同样的问题

**Comment by JCcoder-dick** [comment]
same problem

**Comment by jwangb7111** [comment]
> same problem

Never mind, I have shifted to R4S instead which runs pretty good for last few months.
