### ISSUE TITLE
[Bug Report] vsftpd无法启动

### ISSUE THREAD

**Issue by joebnb** [monlor/MIXBOX-ARCHIVE#263]
**Bug 详情**

在 R3D 下 vsftpd 无法启动

复现：
1. 安装vsftpd
2. 配置 vsftpd
    1. 启动 1
    2. 匿名 0/1 都试过
    3. 添加用户 0/1 与匿名组合都试过
    4. 文件路径都是 /extdisk/sda1/
 3. 启动后回到已安装列表显示未启动

报错
一开始启动的时候提示无法 cp /opt/vsftpd/vsftpd.conf 后来自己到对应路径 touch 了文件，cp 成功，并且看到路径里的文件已经被生成的配置文件覆盖，但是无法启动vsftpd

因为是昨晚上搞的，没又截图，在touch 文件后整个启动过程后续没有报错，但就是启动不起来

```
```

**Comment by monlor** [comment]
建议使用entware，把entware的bin文件link到mixbox也可以

**Comment by joebnb** [comment]
> 建议使用entware，把entware的bin文件link到mixbox也可以

想问下有没有 r3p 上安装 docker 的例子呀，如果安装了 docker 好多事情也就解决了，entware 我这边总说拿不到 packagelist

**Comment by joebnb** [comment]
> 建议使用entware，把entware的bin文件link到mixbox也可以

你好，我在使用 entware 的时候遇到的了一个问题

我的机器是 r3p，选择mixbox 的时候entware 是安装到了外接硬盘上，现在的问题的是开机后在执行 rc.local 的时候外接硬盘还没有被 mount 上，导致在执行source /etc/profile 时不能正确将 entware 的变量加进去。

尝试在 source 前面手动mount /dev/sda1 到/extdisks/sda1，这样可以成功但mount文件系只读（外接硬盘的文件系统是ntfs）

这是尝试过的命令，不知道哪里有问题
```
mount -o remount,rw /dev/sda1 /extdisks/sda1
mount /dev/sda1 /extdisks/sda1
mount -t ntfs -o remount,rw /dev/sda1 /extdisks/sda1
mount -t ntfs-3g -o remount,rw /dev/sda1 /extdisks/sda1
```

现在想请教的是
在外接硬盘上安装的  entware 如何确保是在外接硬盘挂载后再执行命令（是不是只能用循环判断某个挂载后的文件是否存在来判断，还是有更好的方法监听这个事件）
如何让外接硬盘在冷启动后可以立即挂载，我的命令哪里有错吗？

**Comment by joebnb** [comment]
已经搞定，通过 entware 安装了 pure-ftp ，安装完成后依然不能运行，需要修改 /etc/passwd 中 ftp 账号的目录，改到下载目录（具体全线忘了应该需要755权限的目录）

![image](https://user-images.githubusercontent.com/1646883/190859637-242c7186-8753-4693-99ab-123c0d26bd71.png)
